version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "REPLACED_BY_CODEDEPLOY"
        LoadBalancerInfo:
          ContainerName: "mycontainer"
          ContainerPort: 80
