version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 382828593676.dkr.ecr.us-east-1.amazonaws.com)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t service1:$latest .
      - docker tag service1:$IMAGE_TAG 382828593676.dkr.ecr.us-east-1.amazonaws.com/service1:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 382828593676.dkr.ecr.us-east-1.amazonaws.com/service1:latest
      - echo Writing image definitions...
      - printf '[{"name":"mycontainer","imageUri":"%s"}]' 382828593676.dkr.ecr.us-east-1.amazonaws.com/service1:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

