version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 382828593676.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Building Docker image...
      - docker build -t service1:$IMAGE_TAG .
      - docker tag service1:$IMAGE_TAG 382828593676.dkr.ecr.us-east-1.amazonaws.com/service1:$IMAGE_TAG
      - docker tag service1:$IMAGE_TAG 382828593676.dkr.ecr.us-east-1.amazonaws.com/service1:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 382828593676.dkr.ecr.us-east-1.amazonaws.com/service1:$IMAGE_TAG
      - docker push 382828593676.dkr.ecr.us-east-1.amazonaws.com/service1:latest
      - echo Updating taskdef.json with new image tag...
      - sed -i "s|<IMAGE_URI>|382828593676.dkr.ecr.us-east-1.amazonaws.com/service1:$IMAGE_TAG|g" taskdef.json

artifacts:
  files:
    - appspec.yaml
    - taskdef.json
